version: '3.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=''
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    ports:
      - 3307:3306
